version: '3.7'

services:  

  mysql:
    image: mariadb
    container_name: wordpress-database
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306  
    networks:
      - nginxproxymanager_default
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysqlv:/var/lib/mysql

  phpmyadmin:
    image: splattael/phpmyadmin:4.9.7
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    networks:
      - nginxproxymanager_default
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root 
    depends_on:
      - mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8080:80
    networks:
      - nginxproxymanager_default
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mysql
    volumes:
      - wordpressv:/var/www/html
      
  filebrowser:
    image: hurlenko/filebrowser
    container_name: file-browser
    user: "${UID}:${GID}"
    ports:
      - 4443:8080
    networks:
      - nginxproxymanager_default
    volumes:
      - wordpressv:/data
      - filebconfv:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
    depends_on:
      - wordpress   
      
volumes:
  wordpressv:
  mysqlv:
  filebconfv:
networks:
  nginxproxymanager_default:
