version: '3.7'

services:  

  mysql:
    image: linuxserver/mariadb:alpine
    container_name: wordpress-database
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306  
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysqlv:/var/lib/mysql

  phpmyadmin:
    image: splattael/phpmyadmin:4.9.7
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root 
    depends_on:
      - mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.wordpress.wordpress-data == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.wordpress-http.rule=Host(`riocuartonoticias.online`)
        - traefik.http.routers.wordpress-http.entrypoints=http
        - traefik.http.routers.wordpress-http.middlewares=https-redirect
        - traefik.http.routers.wordpress-https.rule=Host(`riocuartonoticias.online`)
        - traefik.http.routers.wordpress-https.entrypoints=https
        - traefik.http.routers.wordpress-https.tls=true
        - traefik.http.routers.wordpress-https.tls.certresolver=le
        - traefik.http.services.wordpress.loadbalancer.server.port=9000
    depends_on:
      - mysql
    volumes:
      - wordpressv:/var/www/html
      
  filebrowser:
    image: hurlenko/filebrowser
    container_name: file-browser
    user: "${UID}:${GID}"
    ports:
      - 4443:8080
    volumes:
      - wordpressv:/data
      - filebconfv:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
    depends_on:
      - wordpress   
 networks:
  traefik-public:
    external: true
 volumes:
  wordpressv:
  mysqlv:
  filebconfv:
  
